import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

/// `fastlane_cli init [--app-name <n>] [--platform ios|android|both]` —
/// scaffold a `cli_profile.yaml` skeleton in cwd.
class InitCommand extends Command<int> {
  InitCommand({
    Directory? workingDirectory,
    StringSink? stdoutSink,
    StringSink? stderrSink,
  }) : _cwd = workingDirectory ?? Directory.current,
       _stdout = stdoutSink ?? stdout,
       _stderr = stderrSink ?? stderr {
    argParser
      ..addOption(
        'app-name',
        help: 'App name written into the scaffold (defaults to "my-app").',
        defaultsTo: 'my-app',
      )
      ..addOption(
        'platform',
        allowed: const <String>['ios', 'android', 'both'],
        defaultsTo: 'both',
        help: 'Which platform comment block to keep.',
      )
      ..addFlag(
        'force',
        defaultsTo: false,
        negatable: false,
        help: 'Overwrite an existing cli_profile.yaml.',
      );
  }

  final Directory _cwd;
  final StringSink _stdout;
  final StringSink _stderr;

  @override
  String get name => 'init';

  @override
  String get description =>
      'Scaffold a minimal cli_profile.yaml in the current directory.';

  @override
  Future<int> run() async {
    final results = argResults!;
    final appName = results.option('app-name') ?? 'my-app';
    final platform = results.option('platform') ?? 'both';
    final force = results.flag('force');

    final target = File(p.join(_cwd.path, 'cli_profile.yaml'));
    if (target.existsSync() && !force) {
      _stderr.writeln(
        'cli_profile.yaml already exists at ${target.path}. '
        'Re-run with --force to overwrite.',
      );
      return 73;
    }

    final yaml = _renderScaffold(appName: appName, platform: platform);
    target.writeAsStringSync(yaml);
    _stdout.writeln('Wrote ${target.path}');
    _stdout.writeln(
      'Edit `app.root_path` to point at your Flutter project root.',
    );
    return 0;
  }

  String _renderScaffold({
    required String appName,
    required String platform,
  }) {
    final iosHint = platform == 'android'
        ? ''
        : '  # iOS lanes inherit from the bundled cli_profile.base.yaml.\n'
            '  # Set IOS_APP_IDENTIFIER + APP_STORE_CONNECT_API_KEY_JSON_PATH\n'
            '  # in your environment (see README → Credentials).\n';
    final androidHint = platform == 'ios'
        ? ''
        : '  # Android lanes inherit from the bundled cli_profile.base.yaml.\n'
            '  # Set ANDROID_PACKAGE_NAME + GOOGLE_PLAY_JSON_KEY_PATH in your\n'
            '  # environment (see README → Credentials).\n';

    return '''# Generated by `fastlane_cli init` — edit before first use.
#
# Everything not declared here (categories, shortcuts, every iOS / Android /
# general action) is inherited from the bundled cli_profile.base.yaml.
# Override an entry by re-declaring it with the same `id`; add new ones by
# giving them a fresh `id`.
app:
  name: $appName
  # Absolute path to your Flutter project root. Required.
  root_path: .
  # Optional. Defaults to "fastlane" (resolved against root_path).
  fastlane_path: fastlane
  # Optional. Defaults to UI language; "tr" or "en".
  default_locale: en

$iosHint$androidHint# Optional. Re-declare action ids here to override base behaviour, or add
# new actions of your own. See README for the schema.
# actions: []
# categories: []
# shortcuts: []
''';
  }
}
